services:
  nextjs:
    image: nextjs
    container_name: nextjs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    # environment:
    #   - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    tty: true
