//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "String(StringLen::None)",
    rename_all = "PascalCase"
)]
pub enum Color {
    Red,
    Orange,
    Brown,
    SkyBlue,
    Blue,
    Green,
    Yellow,
    Purple,
    Pink,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub visible_id: String,
    pub color: Color,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::grand_parent_label_junction::Entity")]
    GrandParentLabelJunction,
    #[sea_orm(has_one = "super::item::Entity")]
    Item,
    #[sea_orm(has_many = "super::parent_label_junction::Entity")]
    ParentLabelJunction,
}

impl Related<super::grand_parent_label_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GrandParentLabelJunction.def()
    }
}

impl Related<super::item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Item.def()
    }
}

impl Related<super::parent_label_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParentLabelJunction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
