//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::grand_parent_label_junction::Entity as GrandParentLabelJunction;
pub use super::item::Entity as Item;
pub use super::label::Entity as Label;
pub use super::object::Entity as Object;
pub use super::parent_label_junction::Entity as ParentLabelJunction;
