services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  neo4j:
    container_name: neo4j
    image: neo4j:5.23.0
    ports:
      - ${NEO4J_HTTP_PORT}:7474 # HTTP (http://localhost:${NEO4J_HTTP_PORT}/browser/)
      - ${NEO4J_BOLT_PORT}:7687 # BOLT (clientのワチャワチャするポート)
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
  meilisearch:
    container_name: meilisearch
    image: "getmeili/meilisearch:prototype-japanese-184"
    volumes:
      #データ部分をマウント
      - ./meili_data:/meili_data
    environment:
      #meili cloudを使わない場合、マスターキーは自分で設定する
      - MEILI_MASTER_KEY=${MASTER_KEY}
      - MEILI_ENV=${MEILI_ENV}
    ports:
      - "${MEILI_PORT}:7700"
    tty: true
