//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub visible_id: String,
    pub parent_id: i32,
    pub parent_visible_id: String,
    pub grand_parent_id: i32,
    pub grand_parent_visible_id: String,
    pub name: String,
    pub product_number: String,
    pub photo_url: String,
    pub record: String,
    pub color: String,
    pub description: String,
    pub year_purchased: Option<i32>,
    pub is_discarded: bool,
    pub connector: Json,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
